POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "emiliana", 
    "name": "emily", 
    "password": "salainen" 
}

###
GET http://localhost:3003/api/users/668b7d10b761fb3e3affafa8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVtaWxpYW5hIiwiaWQiOiI2NjhiN2QxMGI3NjFmYjNlM2FmZmFmYTgiLCJpYXQiOjE3MjA0MTgzOTZ9.sNa4eRuVG3jdEIrkQfs2khgPGjkrr5DtHvtUFLCY5c8
