POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ada", 
    "number": "39-4423"
}

###
DELETE http://localhost:3001/api/persons/6623a41f29c4fa41e93ced24

###
PUT http://localhost:3001/api/persons/6623bb5d1eb3503066dfb10f
Content-Type: application/json

{
    "name": "Mama",
    "number": "909090"
}

